==========================================
SLURM_JOB_ID = 8584783
SLURM_SUBMIT_DIR = /project/kh_mercury_1
SLURM_JOB_NODELIST = mcn52
==========================================
Job ID: 8584783
Job User: pspahwa
Num Cores: 16
Traceback (most recent call last):
  File "/apps/python/3.6/3.6.12/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 633, in __new__
    engine = config.get_option(f"io.excel.{ext}.writer")
  File "/apps/python/3.6/3.6.12/lib/python3.6/site-packages/pandas/_config/config.py", line 233, in __call__
    return self.__func__(*args, **kwds)
  File "/apps/python/3.6/3.6.12/lib/python3.6/site-packages/pandas/_config/config.py", line 105, in _get_option
    key = _get_single_key(pat, silent)
  File "/apps/python/3.6/3.6.12/lib/python3.6/site-packages/pandas/_config/config.py", line 91, in _get_single_key
    raise OptionError(f"No such keys(s): {repr(pat)}")
pandas._config.config.OptionError: "No such keys(s): 'io.excel.csv.writer'"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "updatedDirectSearch.py", line 43, in <module>
    main()
  File "updatedDirectSearch.py", line 34, in main
    news_df.to_excel(save_fp, index = False)
  File "/apps/python/3.6/3.6.12/lib/python3.6/site-packages/pandas/core/generic.py", line 2032, in to_excel
    engine=engine,
  File "/apps/python/3.6/3.6.12/lib/python3.6/site-packages/pandas/io/formats/excel.py", line 730, in write
    writer = ExcelWriter(stringify_path(writer), engine=engine)
  File "/apps/python/3.6/3.6.12/lib/python3.6/site-packages/pandas/io/excel/_base.py", line 637, in __new__
    raise ValueError(f"No engine for filetype: '{ext}'") from err
ValueError: No engine for filetype: 'csv'
srun: error: mcn52: task 0: Exited with exit code 1
